name: "Build and test our eshop"

on:
  pull_request:
    types: [opened]

jobs:
  Install:
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          restore-keys: node_modules-

      - name: Install packages with npm
        run: |
          npm ci

  Build:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          
      - name: Build
        run: |
          npm rebuild node-sass --force
          npm run build -- --colors

  Test:
    needs: Install
    runs-on: ubuntu-latest

    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 10

      - name: Cache Node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: node_modules-${{ hashFiles('**/package-lock.json') }}
          
      - name: Run tests
        run: |
          npm run test -- --colors
